name: Build and Push Docker Image

on:
  push:
    branches:
      - master
      - main
    tags:
      - v*
    paths-ignore: 
      - 'README.md'
      - 'LICENSE'
      - 'deployments/**'
      - 'docker-compose.yml'
      - '.github/**'
  workflow_dispatch:
env:
  DOCKER_USERNAME: jake4
  DOCKER_IMAGE_NAME: council-report-system-frontend
  VITE_API_URL: https://api-council-report-system-portfolio.jack.lat/
  VITE_GOOGLE_MAPS_API_KEY: AIzaSyAMkITHwvzXynS_SG4BVyFzaZp4Z9vju1c
  VITE_RECAPTCHA_SITE_KEY: 6LdmuO4kAAAAAKzXUrQFZTAyZyTLk1ayUWl-Omlo
  VITE_G4A_TRACKING_ID: G-XMMFVF1K3F

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Extract version from tag
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Docker Image (for ${{ env.DOCKER_IMAGE_NAME }})
        uses: docker/build-push-action@v4
        with:
          context: .
          file: deployments/.dockerfile
          push: true
          build-args: |
            VITE_API_URL=${{ env.VITE_API_URL }}
            VITE_GOOGLE_MAPS_API_KEY=${{ env.VITE_GOOGLE_MAPS_API_KEY }}
            VITE_RECAPTCHA_SITE_KEY=${{ env.VITE_RECAPTCHA_SITE_KEY }}
            VITE_G4A_TRACKING_ID=${{ env.VITE_G4A_TRACKING_ID }}
          tags: |
            ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest
            ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ steps.get_version.outputs.version }}